/*
 * This file is generated by the configuration script sys/conf/config.
 *
 * It contains a list the kernel options not prepended to the Makefile
 * as -Dxxxx commands to the compiler.  MAXMEM was moved to param.h leaving
 * only EXTERNALITIMES to be placed in localopts.h
 */

#define EXTERNALITIMES 1
