#!/usr/bin/env python3

#
# Copyright 2021 Jay Logue
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

# 
# @file  Test cases for testing the retro-fuse 2.9BSD filesystem handler.
# 

import os
import sys
import unittest
from fractions import Fraction
from SimhDrivers import BSD29SimhDriver
from FileList import FileListEntry
from FileIOTests import FileIOTests
from RetroFuseTestBase import RetroFuseTestBase

from __main__ import testOpts

class BSD29FileIOTests(RetroFuseTestBase, FileIOTests, unittest.TestCase):
    '''File I/O tests for retro-fuse 2.9BSD filesystem handler
       Note that the majority of tests are implemented in the FileIOTests base class.
    '''

    fsInitOpts = [ '-oinitfs,fssize=10240' ]

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        super().initFS()

    def setUp(self):
        super().setUp()
        self.targetDir = type(self).mountDir

        # 2.9BSD filesystem only supports truncation to 0
        self.testConfig.TruncateFile.Ratios = [ 0 ]

    def test_99_FilesystemCheck(self):
        '''Filesystem Check
           Mounts the filesystem in a simulated 2.9BSD Unix system and verifies
           the integrity and contents of the filesystem against the expected
           list of files/directories left by the file I/O tests.
           '''

        # Unmount the test filesystem from the host system
        self.unmountFS()

        # Adjust the list of files generated by the file ops tests such that they
        # match what is expected to be seen when the filesystem is mounted on a
        # 2.9BSD system (mount point /mnt).
        self.fileList.mapNames(self.mountDir, '/mnt')
        self.fileList.insert(0, FileListEntry('/mnt', type='d'))
        self.fileList.append(FileListEntry('/mnt/lost+found', type='d'))

        # Launch a simulated 2.9BSD system with the test filesystem image attached to
        # /dev/rl2 and perform the following actions...
        debugStream = sys.stderr if testOpts.verbosity >= 2 else None
        with BSD29SimhDriver(simhCmd=testOpts.simhCmd,
                             cwd=self.tempDir,
                             testDiskImage=self.fsImage,
                             debugStream=debugStream) as bsd29:

            # Invoke the 2.9BSD fsck program on the test filesystem image and fail if 
            # any errors are reported.
            (fsckFileCount, fsckBlocksUsed, fsckBlocksFree, fsckErrors) = bsd29.fsck('/dev/rl2')
            self.assertIsNone(fsckErrors)

            # Instruct the simulated system to mount the test filesystem
            bsd29.sendShellCommands('mount /dev/rl2 /mnt')

            # Enumerate the files and directories in the test filesystem, as seen by
            # the simulated system, along with a checksum of their contents.
            bsd29FileList = bsd29.enumFiles('/mnt')

        # Compare the files observed in the simulated system to the list of files generated
        # by the file ops tests.  Fail if there are any differences.
        self.assertFilesystemContents(expectedFileList=self.fileList,
                                      observedFileList=bsd29FileList)

        # Compute the expected number of filesystem inodes in use and fail if this does
        # not match the number returned by fsck.
        expectedInodeCount = 0
        for entry in self.fileList:
            if entry.type == 'f':
                expectedInodeCount += Fraction(1, entry.linkCount)
            else:
                expectedInodeCount += 1
        expectedInodeCount += 1 # +1 for hidden bad block file (inode 1)
        self.assertEqual(fsckFileCount, expectedInodeCount)
