#!/usr/bin/env python3

#
# Copyright 2021 Jay Logue
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

# 
# @file  Test cases for testing the retro-fuse v6 Unix filesystem handler.
# 

import sys
import unittest
import stat
import copy
from fractions import Fraction
from SimhDrivers import V6SimhDriver, V4SimhDriver
from FileList import FileListEntry
from FileIOTests import FileIOTests
from RetroFuseTestBase import RetroFuseTestBase

from __main__ import testOpts

class V6FileIOTests(RetroFuseTestBase, FileIOTests, unittest.TestCase):
    '''File I/O tests for retro-fuse v6 Unix filesystem handler.
       Note that the majority of tests are implemented in the FileIOTests base class.
    '''

    fsInitOpts = [ '-oinitfs' ]
    fsMountOpts = [ '-ofssize=4872,use_ino' ]

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        super().initFS()

    def setUp(self):
        super().setUp()
        self.targetDir = type(self).mountDir

        # v6 filesystem only supports truncation to 0
        self.testConfig.TruncateFile.Ratios = [ 0 ]

    def test_99_CheckV6Compatibility(self):
        '''Check v6 Unix Compatibility
           Mounts the filesystem in a simulated v6 Unix system and verifies
           the integrity and contents of the filesystem against the expected
           list of files/directories left by the file I/O tests.
           '''

        debugStream = sys.stderr if testOpts.verbosity >= 2 else None

        # Unmount the test filesystem from the host system
        type(self).unmountFS()

        # Using the list of files generated by the file ops tests, create a list of
        # files expected to be seen when the filesystem is mounted on a v6 system.
        expectedFileList = copy.deepcopy(self.fileList)
        # - Add directory entry for the filesystem mount point
        expectedFileList.mapNames(self.mountDir, '/mnt')
        expectedFileList.insert(0, FileListEntry('/mnt', type='d'))

        # Compute the expected number of files/directories in use
        expectedFileCount = sum(Fraction(1, entry.linkCount) for entry in expectedFileList if entry.type == 'f')
        expectedDirCount = sum(1 for entry in expectedFileList if entry.type == 'd')
        expectedDevCount = sum(1 for entry in expectedFileList if entry.type == 'b' or entry.type == 'c')

        # Launch a simulated V6 system with the test filesystem image attached to
        # /dev/rk1 and perform the following actions...
        debugStream = sys.stderr if testOpts.verbosity >= 2 else None
        with V6SimhDriver(simhCmd=testOpts.simhCmd,
                          cwd=self.tempDir,
                          testDiskImage=self.fsImage, 
                          debugStream=debugStream) as v6:

            # Invoke the V6 icheck program on the test filesystem image and fail if 
            # any errors are reported.
            (fileCount, dirCount, devCount, usedBlockCount, freeBlockCount, icheckErrs) = v6.icheckFS('/dev/rk1')
            self.assertIsNone(icheckErrs)

            # Instruct the simulated system to mount the test filesystem
            v6.sendShellCommands('/etc/mount /dev/rk1 /mnt')

            # Enumerate the files and directories in the test filesystem, as seen by
            # the simulated system, along with their metadata and a checksum of their
            # contents.
            v6FileList = v6.enumFiles('/mnt')

        # Compare the files observed in the simulated system to the list of files generated
        # by the file ops tests.  Fail if there are any differences.
        self.assertFilesystemContents(expectedFileList=expectedFileList,
                                      observedFileList=v6FileList)

        # Fail if the expected number of files/directories/devices does not match the
        # numbers returned by icheck.
        self.assertEqual(fileCount, expectedFileCount)
        self.assertEqual(dirCount, expectedDirCount)
        self.assertEqual(devCount, expectedDevCount)

    def test_99_CheckV4Compatibility(self):
        '''Check v4 Unix Compatibility
           Mounts the filesystem in a simulated v4 Unix system and verifies
           the integrity and contents of the filesystem against the expected
           list of files/directories left by the file I/O tests.
           '''

        debugStream = sys.stderr if testOpts.verbosity >= 2 else None

        # Unmount the test filesystem from the host system
        type(self).unmountFS()

        # Using the list of files generated by the file ops tests, create a list of
        # files expected to be seen when the filesystem is mounted on a v4 system.
        expectedFileList = copy.deepcopy(self.fileList)
        # - Add directory entry for the filesystem mount point
        expectedFileList.mapNames(self.mountDir, '/mnt')
        expectedFileList.insert(0, FileListEntry('/mnt', type='d'))
        # - Remove the 'sticky' bit from any files or directores. While the on-disk
        #   structure is capable of storing this bit, the v4 ls program will not show it.
        for f in expectedFileList:
            if f.mode:
                f.mode = f.mode & ~stat.S_ISVTX

        # Compute the expected number of files/directories in use
        expectedFileCount = sum(Fraction(1, entry.linkCount) for entry in expectedFileList if entry.type == 'f')
        expectedDirCount = sum(1 for entry in expectedFileList if entry.type == 'd')
        expectedDevCount = sum(1 for entry in expectedFileList if entry.type == 'b' or entry.type == 'c')

        # Launch a simulated v4 Unix system with the test filesystem image attached to
        # /dev/rk1 and perform the following actions...
        with V4SimhDriver(simhCmd=testOpts.simhCmd,
                          cwd=self.tempDir,
                          testDiskImage=self.fsImage, 
                          debugStream=debugStream) as v4:

            # Invoke the V6 icheck program on the test filesystem image and fail if 
            # any errors are reported.
            (fileCount, dirCount, devCount, usedBlockCount, freeBlockCount, checkErrs) = v4.checkFS('/dev/rk1')
            self.assertIsNone(checkErrs)

            # Instruct the simulated system to mount the test filesystem
            v4.sendShellCommands('/etc/mount /dev/rk1 /mnt')

            # Enumerate the files and directories in the test filesystem, as seen by
            # the simulated system, along with their metadata and a checksum of their
            # contents.
            v4FileList = v4.enumFiles('/mnt')

        # Compare the files observed in the simulated v4 system to the list of files generated
        # by the file ops tests.  Fail if there are any differences.
        self.assertFilesystemContents(expectedFileList=expectedFileList,
                                      observedFileList=v4FileList)

        # Fail if the expected number of files/directories/devices does not match the
        # numbers returned by check.
        self.assertEqual(fileCount, expectedFileCount)
        self.assertEqual(dirCount, expectedDirCount)
        self.assertEqual(devCount, expectedDevCount)
