#define	binpath(file)		"/usr/ucb/file"
#define	libpath(file)		"/usr/lib/file"
#define	loclibpath(file)	"/usr/lib/file"
#define	usrpath(file)		"/usr/file"
#define	E_TERMCAP		"/etc/termcap"
#define	B_CSH			"/bin/csh"
